name: Jonathan Taylor Owen
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22566
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#4c4b49'
    - '#131313'
    - '#d9d9d9'
    - '#9c9c9c'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
